### ISSUE TITLE
Some thoughts on the screen cast

### ISSUE THREAD

**Issue by skanev** [testdouble/discovery-testing#1]
I want to share a couple of thoughts on the screencast. Justin asked me to use GitHub issues instead of email so other people can see it. Here it goes.

First of all, I use mocks and I use a similar style of TDD. This is not criticism – I often use the GOOS approach. I just want to discuss some fine points.
1. In the screencast, it does not seem that the tests contributed to the design. You had already decided how to break it down (generate, save, describe) before you started writing tests. The issues you mentioned (e.g. anxiety) could be addressed by doing that "design" work up front and not writing tests with pretty much the same results. At worst, you can create empty stubs for the functions and still reap the same benefits (deciding on the names, having some file structure in place).
2. When finished, it is not obvious what the benefit of the test is. It does not provide much (or anything) in terms of regression. It is also considerably more complex than the code it tests (a simple composition of three functions) and it is not evident why that complexity (or even typing) is worth it.

That being said, I think I say that because of the example – it is quite simple and it does not illustrate the pragmatic benefit of this approach. I think a different example will do better – maybe one that has to integrate with a couple of messy collaborators or one where having those tests helps us spot introducing a bad design decision.

By the way, I don't see much value in test-driving code with isolated collaborators (think Rails controllers). I still do it anyway, since I get value afterwards. Whenever I add code to the controller, I find that the existing tests help me think about the effect of the addition. Fox example, it helps me spot if I introduce a needless collaborator or if I introduce too much coupling. Otherwise I tend to get sloppy in those bits since they are small and understandable enough.

Finally, I really liked the idea about rewriting code vs. reusing. I'm trying to think about a good formulation that doesn't seem too outrageous.

Hope this is useful :)

**Comment by searls** [comment]
I'll respond to each of your numbered points

> In the screencast, it does not seem that the tests contributed to the design. You had already decided how to break it down (generate, save, describe) before you started writing tests. The issues you mentioned (e.g. anxiety) could be addressed by doing that "design" work up front and not writing tests with pretty much the same results. At worst, you can create empty stubs for the functions and still reap the same benefits (deciding on the names, having some file structure in place).

They did not, because (as you pointed out) it was a trivial example and my goal was simply to introduce the practices, not necessarily to sell people on it via revelatory experience (which in my experience can take days to months of project work). It's true that some design up front can address a lot of the same inhibitions, _but_ the benefit of discovery testing is that you're validating your design in extremely small increments with something that will actually execute (in this example, that means creating or getting a reference to a dependency is easy to do, its API is usable and simple, and its parameters and return types get along well with its friends). This benefit is enhanced when used with a typing system to define the data types that need to flow through the system.

> When finished, it is not obvious what the benefit of the test is. It does not provide much (or anything) in terms of regression. It is also considerably more complex than the code it tests (a simple composition of three functions) and it is not evident why that complexity (or even typing) is worth it.

The value of discovery tests is mostly front-loaded, but they're usually really cheap to keep around, so I don't bother deleting them unless I'm planning to also delete the subject code they're paired with. Although, as I pointed out, the tests of leaf nodes in my object graph more closely resemble Classical TDD in that they do have very real regression value. It's a matter of taste/comfort and the expressiveness of your language to determine when it's time to stop reducing the problem and switch over to terminal leaf nodes.

The value in typing through all this and working through it interactively in a tight feedback loop is **tremendous**, because every keystroke—especially in the face of uncertainty—reinforces focused, constructive thoughts about where you're going. It keeps me in forward motion where I'd normally just be staring at a blank screen (or whiteboard), discouraged.

**Comment by skanev** [comment]
Fair enough. This makes total sense to me. I just want to point out two things :)

> ..._but_ the benefit of discovery testing is that you're validating your design in extremely small increments with something that will actually execute (in this example, that means creating or getting a reference to a dependency is easy to do, its API is usable and simple, and its parameters and return types get along well with its friends). **This benefit is enhanced when used with a typing system to define the data types that need to flow through the system.**

I am on the opposite opinion. I claim that a static type system reduces (or eliminates) the benefit of those tests. You can drive the whole process by starting with the root node, and then defining and calling all the functions on the interior nodes, until you get to the leaves, where you can leave empty stubs. The type checker would give you immediate feedback on every step (when you compile) and the tests will add little or no benefit. You still get this flow of focused constructive thoughts, you just lean on the compiler instead of the test suite.

Of course, as soon as you start having some conditional logic, behavior testing on the mocks starts to get valuable, but that's a tangent. My point is that type systems _reduce_ the benefit of those tests, not _enhance_ it.

> The value of discovery tests is mostly front-loaded, but they're **usually really cheap** to keep around, so I don't bother deleting them unless I'm planning to also delete the subject code they're paired with.

Practicing a similar approach to mocks, I've found those tests to get expensive easily. I'll need to take a step back to make my point clear.

Let's explore an `A → B` dependency, where `A` and `B` are different components (classes, functions), and each is tested in isolation. The interface between them is reinforced by the tests twice – one in `B`'s tests, where the functionality is tested and once in `A`'s where the interaction is tested. If `B` has more clients, the reinforcement is stronger.

This makes the `A → B` interface rigid (as in hard to change). It's usually fine if it seldom changes or does so in small ways (additional method here, another parameter there). It is a very different story when the interaction between the two needs to ripped apart and rewired. You either spend effort updating the tests or you do it when deleting and rewriting them from scratch. There is cost to both, especially when they provide regression value due to checking conditional interactions. Had `A` been tested in integration, "ripping out and rewriting" would have gone smoothly due to the presence of the test (the benefit of Classical TDD).

My point is about test-driving this `A → B` interaction. In my experience it works great when I get the interface right the first time. But there are times I don't – I implement the whole thing and _that_ gives me the feedback for a better design idea. I end up rewiring the `A → B` interaction and the isolated tests get in the way. If I delete and write them from scratch, I feel that the first version was a waste of time. If I update them, that's usually tedious and breaks the TDD flow, since I cannot do it in small steps.

This is an instance where this test-first approach hinders me – the real feedback I am after is from how the parts of the "finished" code interact and doing it test-first slows me down, especially when I have to throw my tests out after gaining said feedback. This is why I prefer doing a spike when I'm uncertain about the interaction between the different pieces – I get to explore one (or few) design ideas and then I can revisit them when I TDD the code.

I'll stop here, since I fear I've already strayed far away from the screencast :)
